version: '3.4'

services:
  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - "27017:27017"

  sampleapi:
    image: ${DOCKER_REGISTRY-}sampleapi
    restart: always
    build:
      context: .
      dockerfile: src/SampleApi/Dockerfile
    ports:
      - 5000:80
      - 5001:443
    environment:
      MongoDB__Host: mongodb
    depends_on:
      - mongodb